#!/bin/bash

MPT=/srv/myemsl-ingest

if [ "x$MYEMSL_UNIX_USER" = "x" ]
then
	echo "Unix user is not set."
	exit 1
fi

if [ "x$1" = "x-u" ]
then
	umount "$MPT"
	exit $?
elif [ "x$1" = "x-c" ]
then
	su "$MYEMSL_UNIX_USER" -s /bin/bash -c 'ls "'$MPT'" > /dev/null 2>&1'
	exit $?
else
	if [ "x$MYEMSL_ARCHIVE_USER" = "x" ]
	then
		echo "Archive user is not set."
		exit 1
	fi
	if [ "x$MYEMSL_ARCHIVE_SUBDIR" = "x" ]
	then
		echo "Archive subdir is not set."
		exit 1
	fi
	umask 077
	mkdir -p "$MPT"
	chown "$MYEMSL_UNIX_USER"."$MYEMSL_UNIX_USER" "$MPT"
	buhfs -o subdir="$MYEMSL_ARCHIVE_SUBDIR",no_trash,switch_user="$MYEMSL_UNIX_USER",user="$MYEMSL_ARCHIVE_USER",keytab=/var/hpss/etc/$MYEMSL_UNIX_USER.keytab,no_multiuser,max_write=1048576,rw_buffer_size=33554432 "$MPT"
	exit $?
fi
