#!/bin/bash
#
# Init file for fmds server daemons
#
# chkconfig: 2345 55 25
# description: fmds server daemon
#
# pidfile: /var/run/pacifica_metadata_fmds_writer.pid

# source function library

CHANNEL=fmds
PID_FILE=/var/run/pacifica_metadata_fmds_writer.pid
LOCKFILE=/var/lock/subsys/pacifica_metadata_fmds_writer

. /usr/libexec/pacifica/notification/writer_init
