#!/bin/bash
#
# Init file for jmds server daemons
#
# chkconfig: 2345 55 25
# description: jmds server daemon
#
# pidfile: /var/run/pacifica_metadata_jmds_writer.pid

# source function library

CHANNEL=jmds
PID_FILE=/var/run/pacifica_metadata_jmds_writer.pid
LOCKFILE=/var/lock/subsys/pacifica_metadata_jmds_writer

. /usr/libexec/pacifica/notification/writer_init
