#!/bin/bash
#
# Init file for rmds server daemons
#
# chkconfig: 2345 55 25
# description: rmds server daemon
#
# pidfile: /var/run/pacifica_metadata_rmds_versionclearer.pid

# source function library

CHANNEL=rmds
PID_FILE=/var/run/pacifica_metadata_rmds_versionclearer.pid
LOCKFILE=/var/lock/subsys/pacifica_metadata_rmds_versionclearer
prog="versionclearer"

. /usr/libexec/pacifica/notification/versionclearer_init
