#!/bin/bash
#
# Init file for jmds joiner daemon
#
# chkconfig: 2345 55 25
# description: jmds joiner daemon
#
# pidfile: /var/run/pacifica_metadata_jmds_joiner.pid

# source function library

CHANNEL=fmds
PID_FILE=/var/run/pacifica_metadata_jmds_joiner.pid
LOCKFILE=/var/lock/subsys/pacifica_metadata_jmds_joiner
prog="joiner"

. /usr/libexec/pacifica/notification/versionclearer_init
