#!/usr/bin/python

import sys
from optparse import OptionParser
from pymongo import Connection
from pacifica.notification import *

def add_options(parser):
	parser.add_option('-d', '--db', type='string', action='store', dest='db', default='pacifica_db', help="MongoDB database to use", metavar='D')
	parser.add_option('-n', '--host', type='string', action='store', dest='host', default='', help="MongoDB hostname to use", metavar='H')
	parser.add_option('-p', '--port', type='int', action='store', dest='port', default=27017, help="MongoDB port number to use", metavar='P')
	parser.add_option('-c', '--chanel', type='string', action='store', dest='chanel', default='', help="Chanel to listen on", metavar='C')

def add_usage(parser):
	"""
	Adds a custom usage description string for this module to an OptionParser
	"""
	parser.set_usage("usage: %prog [options] -h host -c chanel")

def check_options(parser):
	if parser.values.host == "":
		sys.stderr.write("You must specify a MongoDB host with -n\n")
		sys.exit(-1)
	if parser.values.chanel == "":
		sys.stderr.write("You must specify a chanel with -c\n")
		sys.exit(-1)

def main():
	parser = OptionParser()
        add_usage(parser)
        add_options(parser)
        parser.parse_args()
        check_options(parser)
	client = Connection(parser.values.host, parser.values.port)
	db = client[parser.values.db]
	scollection = db['notification_versions']
	doc = scollection.find_and_modify(query={'_id': parser.values.chanel}, update={'$inc': {'value': 1}}, upsert=True, new=True)
	version = doc['value']
	collection_name = collection_name_get(db, parser.values.chanel)
	db.create_collection(collection_name, size=1024*1024*100, capped=True)
	collection = db[collection_name]
	collection.insert({'ts':1})
	if version > 1:
		old_collection_name = collection_name_get(db, parser.values.chanel, version=int(version-1))
		print "Droping old collection %s" %(old_collection_name)
		db[old_collection_name].drop()

if __name__ == '__main__':
	sys.exit(main())
