#!/usr/bin/python

import os
import sys
from myemsl.getconfig import getconfig_secret

config = getconfig_secret()

if __name__ == '__main__':
	os.environ['PGPASSWORD'] = config.get('metadata', 'password')	
	os.execvp('psql', ['psql', '-U', config.get('metadata', 'user'), '-h', config.get('metadata', 'host'), config.get('metadata', 'database')] + sys.argv[1:])
