#!/bin/bash
IP=`curl -s -f http://169.254.169.254/latest/meta-data/public-ipv4`
if [ "x$IP" == "x" ]
then
	echo "Could not get public IP."
	exit 1
else
	PUBLICNAME=`nslookup $IP | grep in-addr.arpa | sed 's/.*name\s*=\s*\(.*\)\.$/\1/'`
	if [ "x$PUBLICNAME" == "x" ]
	then
		echo "Could not get public name."
		exit 1
	else
		sed -i 's@<prefix>.*</prefix>@<prefix>https://'"$PUBLICNAME"'/myemsl</prefix>@' /etc/myemsl/services.xml
		sed -i 's@[ \t]*#\?[ \t]*cluster\.name:.*@cluster.name: '"$PUBLICNAME"'@' /etc/elasticsearch/elasticsearch.yml
#HOSTNAME workaround for openstack https://bugs.launchpad.net/neutron/+bug/1175211
		sed -i 's@\(127.0.0.1[ \t].*\)@\1 '"$PUBLICNAME `hostname`"'@' /etc/hosts
	fi
fi
