CREATE ROLE metadata_admins PASSWORD '@PASSWD@' NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN;
CREATE ROLE metadata_readers PASSWORD '@PASSWD2@' NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN;
CREATE DATABASE myemsl_metadata;
GRANT ALL PRIVILEGES ON DATABASE myemsl_metadata to metadata_admins;

