#!/bin/bash

MPT=/srv/myemsl-item

MYEMSL_APACHE_USER=apache

if [ "x$1" = "x-u" ]
then
	umount "$MPT"
	exit $?
elif [ "x$1" = "x-c" ]
then
	su "$MYEMSL_APACHE_USER" -s /bin/bash -c 'ls "'$MPT'" > /dev/null 2>&1'
	exit $?
else
	if [ "x$MYEMSL_ARCHIVE_USER" = "x" ]
	then
		echo "Archive user is not set."
		exit 1
	fi
	if [ "x$MYEMSL_ARCHIVE_SUBDIR" = "x" ]
	then
		echo "Archive subdir is not set."
		exit 1
	fi
	umask 077
	mkdir -p "$MPT"
	chown "$MYEMSL_APACHE_USER"."$MYEMSL_APACHE_USER" "$MPT"
	buhfs -o subdir="$MYEMSL_ARCHIVE_SUBDIR",ro,no_trash,switch_user="$MYEMSL_APACHE_USER",user="$MYEMSL_ARCHIVE_USER",keytab=/var/hpss/etc/svc-myemsl.keytab,no_multiuser,max_write=1048576,rw_buffer_size=33554432 "$MPT"
	exit $?
fi
